version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.6.2
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1

  lib-test:
    depends_on:
      - elasticsearch
    build:
      context: ../
      dockerfile: dockerfiles/Dockerfile.test
    environment:
      ES_HOST: http://elasticsearch:9200
    command: ["clojure", "-A:test", "-i", "integration"]
