name: Deploy to clojars

on:
  push:
    tags:
      - lazy-elasticsearch-scroll-*

jobs:
  deploy-to-clojars:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.0.2

      - name: Cache maven deps
        uses: actions/cache@v3.0.2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/deps.edn') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Prepare java
        uses: actions/setup-java@v3.3.0
        with:
          java-version: 17

      - name: Publish to Clojars
        run: mvn --batch-mode -s clojars-settings.xml deploy
        env:
          CLOJARS_USERNAME: ${{ secrets.CLOJARS_USERNAME }}
          CLOJARS_PASSWORD: ${{ secrets.CLOJARS_PASSWORD }}
