name: Deploy to clojars

on: [push]

jobs:
  deploy-to-clojars:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Cache maven deps
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/deps.edn') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Prepare java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Publish to Clojars
        run: |
          mvn --batch-mode -s clojars-settings.xml \
            -Dtag=lazy-elasticsearch-scroll-1.0.0 release:prepare \
            -DreleaseVersion=1.0.0 \
            -DdevelopmentVersion=2.0.0-SNAPSHOT
          mvn --batch-mode -s clojars-settings.xml release:perform
        env:
          CLOJARS_USERNAME: ${{ secrets.CLOJARS_USERNAME }}
          CLOJARS_PASSWORD: ${{ secrets.CLOJARS_PASSWORD }}
