name: Tests

on:
  push:
    branches:
      - '*'
      - '!lazy-elasticsearch-scroll-*'
    tags:
      - '!lazy-elasticsearch-scroll-*'
    paths-ignore:
      - 'pom.xml'

jobs:
  unit-test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.0.2

      - name: Cache maven deps
        uses: actions/cache@v3.0.2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/deps.edn') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Prepare java
        uses: actions/setup-java@v3.3.0
        with:
          java-version: 1.8
          distribution: 'zulu'

      - name: Install clojure tools-deps
        uses: DeLaGuardo/setup-clojure@master
        with:
          cli: 1.11.1.1113

      - name: Unit Tests
        run: clojure -A:dev:test -e integration

  integration-test:
    name: Integration Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # Set N number of parallel jobs you want to run tests on.
        # Use higher number if you have slow tests to split them on more parallel jobs.
        # Remember to update ci_node_index below to 0..N-1
        ci_node_total: [2]
        # set N-1 indexes for parallel jobs
        # When you run 2 parallel jobs then first job will have index 0, the second job will have index 1 etc
        ci_node_index: [0]
        java: ["1.8", "11", "14"]
        elasticsearch: ["elasticsearch:6.8.12", "docker.elastic.co/elasticsearch/elasticsearch:7.11.0"]
    services:
      elasticsearch:
        image: ${{ matrix.elasticsearch }}
        ports:
          - 9200/tcp
        options: -e="discovery.type=single-node" --health-cmd="curl http://localhost:9200/_cluster/health" --health-interval=10s --health-timeout=5s --health-retries=10
    steps:
      - uses: actions/checkout@v3.0.2

      - name: Cache maven deps
        uses: actions/cache@v3.0.2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/deps.edn') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Prepare java
        uses: actions/setup-java@v3.3.0
        with:
          java-version: ${{ matrix.java }}
          distribution: 'zulu'

      - name: Install clojure tools-deps
        uses: DeLaGuardo/setup-clojure@master
        with:
          cli: 1.11.1.1113

      - name: Integration Tests
        env:
          ES_HOST: http://localhost:${{ job.services.elasticsearch.ports[9200] }}
        run: |
          echo $ES_HOST
          clojure -A:dev:test -i integration
